version: '20.10.10'

services: 
    sqlite3db:
      image: keinos/sqlite3:latest
      volumes:
      - db:/server/database.db
      networks:
      - backend
    server:
      depends_on:
        - sqlite3db
      build: ./server
      restart: unless-stopped
      ports:
        - 5000:5001
      environment:
        - CLIENT_ORIGIN=http://127.0.0.1:3000
      networks:
        - backend
        - frontend
    client:
      depends_on:
      - server
      build:
        context: ./client
      ports:
        - 3000:3001
      networks:
      - frontend

volumes: 
  db:

networks:
  backend:
  frontend: